### PR TITLE
Glove vibration

### PR DESCRIPTION
**Pull request by codesalad**
Added haptic feedback.

Thank me later.

### CODE REVIEW

**Comment by MKlaassen** [comment]
@codesalad 
This branch has some merge conflicts, did you merge master into your branch before making this pull request?

**Comment by codesalad** [comment]
You mean did I merge it 7 hrs ago? Yes.

I'm going to fix it instead of closing the request.

**Comment by codesalad** [comment]
Fixed :8ball:

**Comment by MKlaassen** [comment]
@codesalad, your last commit was half an hour ago. Is this branch ready for merge with master or are you still working on it? We should only make pull requests when a branch is ready for merge.

**Pull request merged**
