### PR TITLE
Manus

### PR DESCRIPTION
**Pull request by brdofparadise**

### CODE REVIEW

**Comment by codesalad** [comment]
Code looks fine, needs testing with Manus before merging.

**Comment by vwigmore** [comment]
What functionality is added in this pr? There is no description

**Comment by brdofparadise** [comment]
When the basket is picked up with the Manus it looks more realistic.

**Comment by codesalad** [comment]
Testing the branch now before merging.

**Comment by codesalad** [comment]
This can probably be merged now. But item position still needs to be fixed later.

**Pull request merged**
