### PR TITLE
refactored the handcontroller

### PR DESCRIPTION
**Pull request by codesalad**
Hey, I've refactored the handcontroller. #36 

Check if it works for you.

### CODE REVIEW

**Comment by mariasimi** [comment]
Everything seems to work fine

**Comment by vwigmore** [comment]
Since we're going towards working with interfaces, for making testing easier, could you add an interface IHand or something? Overall it look good. :+1:

**Comment by codesalad** [comment]
Of course I could. And I will soon.

**Comment by codesalad** [comment]
I have added the interface for hand.

**Comment by vwigmore** [comment]
Yes!!! This is exactly what i meant!

**Pull request merged**
