### PR TITLE
Shorten method length

### PR DESCRIPTION
**Pull request by mariasimi**
I have changed some methods according to SIG standards.
Please checkout this branch.

### CODE REVIEW

**Comment by codesalad** [comment]
Nice. I've yet to test this with hardware but it should work just fine.

I do however have suggestions for better method names:

**Grab.cs**
`DropObjectHelp()` -> `DropInBasket()` (the function only applies to objects you want to drop in the basket)

`UpdateGrabbedObjectHelp()` -> `UpdateGrabbedBasket()` (only applies to basket)

**MouseGrabController.cs**
`UpdateHelp(RaycastHit h)` -> `UpdateCastedRay(RaycastHit h)` (clear indication of function)

`RayCastHitHelp(RaycastHit hit)` -> `OnMouseEvent(RaycastHit hit)` (clarity: mouse event specific)

**Hand.cs**
`UpdateHandHelp(float[] f)` -> `UpdateFingers(float[] f)` (clarity: only applies to fingers)

In the new **Manager.cs**, `readConfig()` is probably too long as well - which I'll fix now.

**Comment by vwigmore** [comment]
@msimidzioski @codesalad 

Concerning method names, I think it would be more clear if instead of using the "help" suffix we'd use names that actually describe what is happening.

**Comment by mariasimi** [comment]
Manager.cs is fixed and the methods are renamed

**Comment by codesalad** [comment]
Super duper job.

**Pull request merged**
