### PR TITLE
Manager.cs file now contains global settings #21

### PR DESCRIPTION
**Pull request by vwigmore**
Manager script now has global settings for highlighting selected object
and gesture based movement.

### CODE REVIEW

**Comment by brdofparadise** [comment]
It works. Good that you didn't forget to add comments. :)

**Comment by codesalad** [comment]
Looks good, can you remove the "I'm alive" debug line, this was just a test I forgot to remove.

**Comment by vwigmore** [comment]
@codesalad Removed the debug line

**Comment by codesalad** [comment]
@vwigmore Super duper. Merging.

**Pull request merged**
