### PR TITLE
Kinect manus

### PR DESCRIPTION
**Pull request by vwigmore**
Merged master into this branch for making sure final merge would not result in error.
Please pull and test for eventual errors

### CODE REVIEW

**Comment by MKlaassen** [comment]
We have one last change for this branch, merging can be done afterwards.

**Comment by mariasimi** [comment]
The branch can now  be merged.

**Comment by vwigmore** [comment]
Those new features look really nice!! :+1:

**Comment by codesalad** [comment]
Looks Ok.

**Comment by brdofparadise** [comment]
It looks good :)

**Pull request merged**
