### PR TITLE
added config file, fixed grabbing!

### PR DESCRIPTION
**Pull request by codesalad**
Test if it works!

### CODE REVIEW

**Comment by vwigmore** [comment]
I get several errors in the Unity console about the 3rd party packages

**Comment by codesalad** [comment]
yep wilk fix

**Comment by vwigmore** [comment]
it is still not fixed

**Comment by codesalad** [comment]
I believe that it works now :8ball:

**Comment by vwigmore** [comment]
Yes it does

**Comment by MKlaassen** [comment]
Looks good! can be merged

**Pull request merged**
